//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KU_Students
    {
        public int Student_ID { get; set; }
        public string Organization_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public bool Resident { get; set; }
        public byte[] Photo { get; set; }
        public string Address { get; set; }
        public string Meal_Plan { get; set; }
        public bool Meal_Plan_Status { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}
