//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Stations = new HashSet<Station>();
        }
    
        public int Order_ID { get; set; }
        public System.DateTime Order_DateTime { get; set; }
        public string Order_Status { get; set; }
        public System.DateTime Fulfillment_DateTime { get; set; }
        public string Station_Name { get; set; }
        public string Item { get; set; }
        public int Item_Qty { get; set; }
        public decimal Gross_Price { get; set; }
        public decimal Tax { get; set; }
        public decimal Net_Price { get; set; }
        public string Payment_Method { get; set; }
        public decimal Paid { get; set; }
        public decimal Change { get; set; }
    
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station> Stations { get; set; }
    }
}
